"// ... existing code ...
if (current) {
        const zeroTermico = (current as any)?.freezingLevel ?? 3000; // Fixed: Added type assertion to access freezingLevel
        const precip = current.precipitation ?? 0;
// ... rest of the code ...