character escaping in span text">
...
          <div className="w-4 h-4 rounded" style={{ background: "linear-gradient(90deg, #2ecc71, #f1c40f, #e67e22, #e74c3c)" }} />
          <span>Vento: verde ≤5 · giallo ≤10 · arancio ≤20 · ross&nbsp;> 20 km/h</span>
        </div>
...